// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/google/wire"
	"github.com/mengdu/gocrontab/internal/core"
)

// Injectors from wire.go:

func Build() (*Injector, error) {
	manager := core.New()
	injector := &Injector{
		Manager: manager,
	}
	return injector, nil
}

// wire.go:

var set = wire.NewSet(wire.Struct(new(Injector), "*"), core.Set)

type Injector struct {
	Manager *core.Manager
}
